
import { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Sourdough Bread',
    price: 7.99,
    description: 'Traditional sourdough with a crispy crust and soft interior',
    longDescription: 'Our signature sourdough is made with a 24-hour fermentation process, resulting in a complex flavor profile with just the right amount of tanginess. Each loaf is hand-shaped and baked on a stone hearth for the perfect crust.',
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80',
    category: 'bread',
    featured: true,
    ingredients: ['Organic flour', 'Water', 'Salt', 'Sourdough starter'],
    allergens: ['Wheat'],
    inStock: true,
  },
  {
    id: '2',
    name: 'Chocolate Chip Cookies',
    price: 12.99,
    description: 'Soft-baked cookies with premium chocolate chunks',
    longDescription: 'These are not your ordinary chocolate chip cookies. Made with brown butter and a blend of dark and milk chocolate chunks, these cookies have crispy edges and a gooey center. Each batch is carefully mixed and portioned for consistent quality.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1964&q=80',
    category: 'cookies',
    featured: true,
    ingredients: ['Organic flour', 'Butter', 'Brown sugar', 'Eggs', 'Chocolate chunks', 'Vanilla extract', 'Baking soda', 'Salt'],
    allergens: ['Wheat', 'Dairy', 'Eggs'],
    inStock: true,
  },
  {
    id: '3',
    name: 'Blueberry Muffins',
    price: 3.99,
    description: 'Moist muffins packed with fresh blueberries',
    longDescription: 'Our blueberry muffins are made with locally-sourced blueberries when in season and a hint of lemon zest to brighten the flavor. The muffin base is light and fluffy, and the top has a delicate sugar coating that gives a slight crunch.',
    image: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1780&q=80',
    category: 'pastries',
    ingredients: ['Organic flour', 'Butter', 'Sugar', 'Eggs', 'Milk', 'Blueberries', 'Lemon zest', 'Baking powder', 'Salt'],
    allergens: ['Wheat', 'Dairy', 'Eggs'],
    inStock: true,
  },
  {
    id: '4',
    name: 'Artisan Croissants',
    price: 3.49,
    description: 'Flaky, buttery croissants baked to golden perfection',
    longDescription: 'Our croissants are made through a three-day process, with premium European-style butter folded into a yeasted dough to create dozens of delicate layers. The result is an incredibly flaky, buttery pastry with a honeycomb interior.',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1926&q=80',
    category: 'pastries',
    featured: true,
    ingredients: ['Organic flour', 'European-style butter', 'Sugar', 'Yeast', 'Milk', 'Salt'],
    allergens: ['Wheat', 'Dairy'],
    inStock: true,
  },
  {
    id: '5',
    name: 'Cinnamon Raisin Bread',
    price: 6.99,
    description: 'Soft bread swirled with cinnamon and studded with raisins',
    longDescription: 'Our cinnamon raisin bread features a tender crumb with swirls of cinnamon sugar and plump, juicy raisins in every slice. Perfect for breakfast toast or as a base for bread pudding.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1772&q=80',
    category: 'bread',
    ingredients: ['Organic flour', 'Butter', 'Sugar', 'Eggs', 'Milk', 'Cinnamon', 'Raisins', 'Yeast', 'Salt'],
    allergens: ['Wheat', 'Dairy', 'Eggs'],
    inStock: true,
  },
  {
    id: '6',
    name: 'Lemon Tart',
    price: 5.99,
    description: 'Buttery shortcrust filled with tangy lemon curd',
    longDescription: 'Our lemon tart strikes the perfect balance between sweet and tart. The shortcrust pastry is made with high-quality butter, and the filling is a smooth, zesty lemon curd topped with a light dusting of powdered sugar.',
    image: 'https://images.unsplash.com/photo-1566121933407-3c7ccdd26763?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80',
    category: 'pastries',
    ingredients: ['Organic flour', 'Butter', 'Sugar', 'Eggs', 'Lemons', 'Cream'],
    allergens: ['Wheat', 'Dairy', 'Eggs'],
    inStock: true,
  },
];

export const categories = [
  { id: 'all', name: 'All Products' },
  { id: 'bread', name: 'Artisan Breads' },
  { id: 'pastries', name: 'Pastries' },
  { id: 'cookies', name: 'Cookies & Treats' },
];
